[package]
name = "hexdb_core"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.15.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "time", "json"] }
dashmap = "6.1.0"
async-trait = "0.1"
blake3 = "1.8.2"
ulid = { version = "1.2.1", features = ["serde"] }
rust_decimal = { version = "1.37.1", features = ["serde"] }
base64 = "0.22.1"
chrono = { version = "0.4.41", features = ["serde"] }
aes-gcm = "0.10.3"
rand = { version = "0.9.1", features = ["std"] }
rand_core = "0.9.3"
hex = "0.4.3"
zstd = "0.13.3"
getrandom = "0.3.3"
byteorder = "1.5"
argon2 = "0.5.3"
futures = "0.3.31"
reed-solomon-simd = "3"
toml = "0.8"
hmac = "0.12"
sha1 = "0.10"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
sqlparser = "0.63.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_Security", "Win32_System_JobObjects", "Win32_System_Threading"] }
