[package]
name = "hexdb_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hexdb"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
tokio = { version = "1.37", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
shellexpand = "3.1.1"
serde_json = "1.0.140"
toml = "0.8.22"
hexdb_core = { path = "../hexdb_core" }
base64 = "0.22"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Threading", "Win32_System_ProcessStatus"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal"] }
