[package]
name = "hexdb_api"
version = "0.1.0"
edition = "2021"

[dependencies]
hexdb_core = { path = "../hexdb_core" }
hexdb_query = { path = "../hexdb_query" }
async-graphql = "7.0"
tokio = { version = "1.37", features = ["full"] }
axum = "0.8.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"
hyper = { version = "1", features = ["server"] }
serde_json = "1.0.140"
base64 = "0.22.1"
serde = { version = "1.0.219", features = ["derive"] }
chrono = "0.4.41"
tower-http = { version = "0.6.4", features = ["fs"] }
ulid = "1.2.1"
futures = "0.3"
axum-server = { version = "0.7", features = ["tls-rustls"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
