[network]
api_endpoint = "127.0.0.1:7700"
discovery_endpoint = "127.0.0.1:7702"
lattice_name = "Nebula Prime"

[identity]
role = "auto" # auto | overseer | harvester | replicant

[security]
admin_login = "hexdbadmin"
admin_password = "hexdbadmin"
admin_email = "admin@hexdb.ai"

[memory]
ram_mb = 1024
ttl_scan_frequency = 600
vertex_integrity_check_frequency = 300

[storage]
path = "./.hexdb"
disk_mb = 16384
encryption_key = "base64:eTdfrgJPvGOy7tJPI8z7CyO5Z9TT+biDWK+SCVa7OfA="
compaction_frequency = 180
wal_sync = true # fsync the WAL before acknowledging writes
wal_flush_check_frequency = 60

[compression]
compression_level = 0
