[network]
engine_endpoint = "127.0.0.1:7700"
query_endpoint = "127.0.0.1:7701"
discovery_endpoint = "127.0.0.1:7702"

[memory]
ram_mb = 1024

[storage]
disk_mb = 16384
encryption_key = "base64:eTdfrgJPvGOy7tJPI8z7CyO5Z9TT+biDWK+SCVa7OfA="

[compression]
compression_level = 0
